"""Base strategy interface for backtesting."""

from __future__ import annotations

from abc import ABC, abstractmethod
from enum import StrEnum
from typing import Any

import pandas as pd
from pydantic import BaseModel, Field


class SignalType(StrEnum):
    """Trading signal type."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class Signal(BaseModel):
    """A trading signal generated by a strategy.

    Attributes:
        date: Signal date (YYYY-MM-DD).
        ticker: Target stock ticker.
        signal_type: Buy, sell, or hold.
        strength: Signal confidence (0.0 to 1.0).
        reason: Human-readable explanation.
        allocation: Suggested portfolio allocation fraction (0.0 to 1.0).
    """

    date: str
    ticker: str
    signal_type: SignalType
    strength: float = 0.5
    reason: str = ""
    allocation: float = 0.1


class BaseStrategy(ABC):
    """Abstract base class for backtesting strategies.

    Subclasses must implement:
        - name: Strategy identifier
        - generate_signals: Produce buy/sell/hold signals for a given date

    Example::

        class MyStrategy(BaseStrategy):
            @property
            def name(self) -> str:
                return "my_strategy"

            def generate_signals(self, date, prices, context):
                # Analyze and return signals
                return [Signal(date=date, ticker="AAPL", signal_type=SignalType.BUY)]
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique strategy name."""

    @property
    def description(self) -> str:
        """Human-readable strategy description."""
        return ""

    @abstractmethod
    def generate_signals(
        self,
        date: str,
        prices: dict[str, pd.DataFrame],
        context: dict[str, Any] | None = None,
    ) -> list[Signal]:
        """Generate trading signals for a given date.

        Args:
            date: Current simulation date (YYYY-MM-DD).
            prices: Dict mapping ticker to OHLCV DataFrame
                    (rows up to and including `date`).
            context: Optional extra data (sentiment scores, indicators, etc).

        Returns:
            List of Signal objects.
        """

    def initialize(self, tickers: list[str], **kwargs: Any) -> None:
        """Called once before backtesting starts.

        Override to set up strategy state.

        Args:
            tickers: List of tickers being tested.
            **kwargs: Additional config.
        """

    def on_trade(self, ticker: str, signal_type: SignalType, date: str) -> None:
        """Called after a trade is executed.

        Override to update strategy state.

        Args:
            ticker: Traded ticker.
            signal_type: Whether it was a buy or sell.
            date: Trade date.
        """
